apiVersion: v1
kind: ServiceAccount
metadata: 
  name: rds-access-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::245582572290:role/eks-s3-access


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-connect-creds
  namespace: default
data:
  PROD: "prod"
  DB_HOST: "spylyp-db.cgqtqi4cjycq.us-west-2.rds.amazonaws.com"
  DB_NAME: "shop"
  DB_PORT: "5432"
  DB_USER: "postgres"
