apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-secret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sviatoslavpylyp/devops-flask-k8s.git
    targetRevision: HEAD
    path: ./envs/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Replace=true
    - CreateNamespace=false
