apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:sviatoslavpylyp/devops-flask-k8s.git
    targetRevision: HEAD
    path: ./argo/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      