apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: py-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sviatoslavpylyp/devops-flask-k8s.git
    targetRevision: HEAD
    path: ./manifests/py_service
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Replace=true
    - CreateNamespace=false
      